CC = gcc
CFLAGS= -g -std=c99 -Wall -fsanitize=address,undefined

all: memgrind memtest customtest

memgrind: memgrind.o mymalloc.o
	$(CC) $(CFLAGS) $^ -o $@

memtest: memtest.o mymalloc.o 
	$(CC) $(CFLAGS) $^ -o $@

customtest: customtest.o mymalloc.o
	$(CC) $(CFLAGS) $^ -o $@

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

memgrind.o memtest.o mymalloc.o customtest.o: mymalloc.h
